import { useCallback, useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import StatusBadge from '../components/StatusBadge';
import { useAuth } from '../features/auth/AuthContext';
import { usePageTitle } from '../hooks/usePageTitle';
import { formatDate, formatDateTime, statusMeta } from '../lib/applications';
import { deleteApplication, getApplication, getApplicationHistory, updateApplicationStatus } from '../services/applications';

export default function ApplicationDetailPage() {
  const { id } = useParams();
  const { token } = useAuth(); const navigate = useNavigate();
  const [application, setApplication] = useState(null); const [history, setHistory] = useState([]); const [error, setError] = useState(null); const [loading, setLoading] = useState(true);
  const requestVersion = useRef(0);
  const [nextStatus, setNextStatus] = useState(''); const [statusNote, setStatusNote] = useState(''); const [statusError, setStatusError] = useState(''); const [statusSaving, setStatusSaving] = useState(false);
  const [confirming, setConfirming] = useState(false); const [deleteError, setDeleteError] = useState(''); const [deleting, setDeleting] = useState(false);
  usePageTitle('Detail Lamaran');
  const load = useCallback(async () => { const version = ++requestVersion.current; setLoading(true); setError(null); try { const [nextApplication, nextHistory] = await Promise.all([getApplication(token, id), getApplicationHistory(token, id)]); if (version === requestVersion.current) { setApplication(nextApplication); setHistory(nextHistory); setNextStatus(nextApplication.status); } } catch (requestError) { if (version === requestVersion.current) setError(requestError); } finally { if (version === requestVersion.current) setLoading(false); } }, [token, id]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => () => { requestVersion.current += 1; }, []);
  const saveStatus = async (event) => { event.preventDefault(); setStatusError(''); if (nextStatus === application.status) { setStatusError('Pilih status yang berbeda untuk memperbarui progres.'); return; } setStatusSaving(true); try { await updateApplicationStatus(token, id, { status: nextStatus, ...(statusNote.trim() ? { note: statusNote.trim() } : {}) }); setStatusNote(''); await load(); } catch (requestError) { setStatusError(requestError.message); } finally { setStatusSaving(false); } };
  const remove = async () => { setDeleting(true); setDeleteError(''); try { await deleteApplication(token, id); navigate('/applications', { replace: true, state: { notice: 'Lamaran berhasil dihapus.' } }); } catch (requestError) { setDeleteError(requestError.message); } finally { setDeleting(false); } };
  if (loading) return <DetailSkeleton />;
  if (error?.status === 404) return <NotFound />;
  if (error) return <RequestError message={error.message} retry={load} />;
  return <main className="mx-auto max-w-6xl px-5 py-8 sm:px-8 sm:py-10">
    <Link className="text-sm font-semibold text-signal hover:underline" to="/applications">← Kembali ke Applications</Link>
    <div className="mt-5 flex flex-wrap items-start justify-between gap-5"><div><p className="font-mono text-xs font-semibold uppercase tracking-[0.15em] text-signal">Application</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-ink">{application.companyName}</h1><p className="mt-2 text-lg text-slate-600">{application.jobTitle}</p></div><div className="flex flex-wrap gap-2"><Link className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-white" to={`/applications/${id}/edit`}>Edit</Link><button className="rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-700 hover:bg-red-50" onClick={() => setConfirming(true)}>Hapus</button></div></div>
    <div className="mt-6"><StatusBadge status={application.status} /></div>
    <section className="mt-6 grid gap-4 lg:grid-cols-[minmax(0,1fr)_20rem]"><div className="rounded-xl border border-line bg-white p-5 sm:p-6"><h2 className="font-semibold text-ink">Informasi lamaran</h2><dl className="mt-5 grid gap-x-8 gap-y-5 sm:grid-cols-2"><Info label="Tanggal melamar" value={formatDate(application.appliedAt)} /><Info label="Lokasi" value={application.location} /><Info label="Tipe kerja" value={application.workType} /><Info label="Sumber lowongan" value={application.source} /><Info label="Rentang gaji" value={application.salaryRange} /><Info label="Follow-up berikutnya" value={application.nextFollowUpAt && formatDate(application.nextFollowUpAt)} /><Info label="Nama kontak" value={application.contactName} /><Info label="Email kontak" value={application.contactEmail} /><Info label="URL lowongan" value={application.applicationUrl && <a className="break-all text-signal hover:underline" href={application.applicationUrl} rel="noreferrer" target="_blank">Buka lowongan</a>} /><Info label="Terakhir diperbarui" value={formatDateTime(application.updatedAt)} /></dl>{application.notes && <div className="mt-6 border-t border-line pt-5"><p className="text-sm font-medium text-slate-600">Catatan</p><p className="mt-2 whitespace-pre-wrap leading-7 text-ink">{application.notes}</p></div>}</div><StatusForm current={application.status} error={statusError} loading={statusSaving} note={statusNote} onNote={setStatusNote} onStatus={setNextStatus} onSubmit={saveStatus} value={nextStatus} /></section>
    <section className="mt-6 rounded-xl border border-line bg-white p-5 sm:p-6"><h2 className="font-semibold text-ink">Riwayat status</h2>{history.length ? <ol className="mt-5 space-y-5 border-l border-line pl-5">{history.map((item) => <li key={item.id} className="relative"><span className="absolute -left-[1.78rem] top-1.5 h-2.5 w-2.5 rounded-full bg-signal ring-4 ring-white" /><div className="flex flex-wrap items-center gap-2"><StatusBadge status={item.newStatus} /><span className="text-xs text-slate-500">{formatDateTime(item.createdAt)}</span></div>{item.oldStatus && <p className="mt-1 text-sm text-slate-600">Dari {statusMeta[item.oldStatus]?.[0] || item.oldStatus}</p>}{item.note && <p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{item.note}</p>}</li>)}</ol> : <p className="mt-4 text-sm text-slate-600">Belum ada riwayat status.</p>}</section>
    {confirming && <DeleteDialog application={application} error={deleteError} loading={deleting} onCancel={() => { setConfirming(false); setDeleteError(''); }} onConfirm={remove} />}
  </main>;
}

function Info({ label, value }) { return value ? <div><dt className="text-sm text-slate-500">{label}</dt><dd className="mt-1 text-sm font-medium text-ink">{value}</dd></div> : null; }
function StatusForm({ current, value, onStatus, note, onNote, onSubmit, error, loading }) { return <form className="h-fit rounded-xl border border-line bg-white p-5" onSubmit={onSubmit}><h2 className="font-semibold text-ink">Perbarui status</h2><p className="mt-1 text-sm leading-6 text-slate-600">Status saat ini: {statusMeta[current]?.[0]}</p>{error && <p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}<label className="mt-5 block"><span className="form-label">Status baru</span><select className="form-input" onChange={(event) => onStatus(event.target.value)} value={value}>{Object.entries(statusMeta).map(([status, [label]]) => <option key={status} value={status}>{label}</option>)}</select></label><label className="mt-4 block"><span className="form-label">Catatan perubahan <span className="font-normal text-slate-400">(opsional)</span></span><textarea className="form-input min-h-24 resize-y" maxLength="5000" onChange={(event) => onNote(event.target.value)} value={note} /></label><button className="btn-primary mt-5 w-full" disabled={loading} type="submit">{loading ? 'Memperbarui…' : 'Simpan status'}</button></form>; }
function DeleteDialog({ application, error, loading, onCancel, onConfirm }) { return <div aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-ink/40 p-5" role="dialog" aria-labelledby="delete-title"><div className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl"><h2 id="delete-title" className="text-lg font-semibold text-ink">Hapus lamaran?</h2><p className="mt-2 text-sm leading-6 text-slate-600">Lamaran <strong>{application.jobTitle}</strong> di <strong>{application.companyName}</strong> akan dihapus permanen.</p>{error && <p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button className="rounded-lg px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-100" disabled={loading} onClick={onCancel}>Batal</button><button className="rounded-lg bg-red-700 px-3 py-2 text-sm font-semibold text-white hover:bg-red-800 disabled:opacity-60" disabled={loading} onClick={onConfirm}>{loading ? 'Menghapus…' : 'Hapus lamaran'}</button></div></div></div>; }
function NotFound() { return <main className="mx-auto max-w-3xl px-5 py-10"><section className="rounded-xl border border-dashed border-slate-300 bg-white p-8"><h1 className="text-xl font-semibold text-ink">Lamaran tidak ditemukan.</h1><Link className="mt-4 inline-block text-sm font-semibold text-signal hover:underline" to="/applications">Kembali ke Applications</Link></section></main>; }
function RequestError({ message, retry }) { return <main className="mx-auto max-w-3xl px-5 py-10"><section role="alert" className="rounded-xl border border-red-200 bg-red-50 p-6"><p className="font-semibold text-red-800">Detail belum dapat dimuat</p><p className="mt-1 text-sm text-red-700">{message}</p><button className="mt-4 text-sm font-semibold text-red-800 underline" onClick={retry}>Coba lagi</button></section></main>; }
function DetailSkeleton() { return <main className="mx-auto max-w-6xl animate-pulse px-5 py-10"><div className="h-4 w-36 rounded bg-slate-200" /><div className="mt-6 h-10 w-72 rounded bg-slate-200" /><div className="mt-8 h-80 rounded-xl bg-slate-200" /></main>; }
